name: migration-warning-on-release-branches

on:
  pull_request:
    branches:
      - release/*
    paths:
      - 'db/migrate/**.rb'
      - 'modules/**/db/migrate/*.rb'

jobs:
  danger:
    if: github.repository == 'opf/openproject'
    runs-on: [ubuntu-latest]
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3.4'
      - uses: MeilCli/danger-action@v6
        with:
          danger_file: 'Dangerfile'
          danger_id: 'danger-pr'
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
